### DISCUSSION TITLE
MissingRegion

### DISCUSSION THREAD

**Discussion by roughnecks** [ente-io/ente#1403] [Q&A] [answered]
Hi,

I have this error in docker's log for ente sel-hosted server:

```
museum-1           | ERRO[0195]handler.go:46 Error Request failed                                error= --- at /etc/ente/pkg/api/file.go:92 (FileHandler.GetUploadURLs) ---
museum-1           |  --- at /etc/ente/pkg/controller/file.go:253 (FileController.GetUploadURLs) ---
museum-1           |  --- at /etc/ente/pkg/controller/file.go:825 (FileController.getObjectURL) ---
museum-1           | Caused by: MissingRegion: could not find region configuration
```

Nothing gets uploaded and in my export dir I see this for each album:

```
$ ls -l
total 16
drwxr-xr-x 3 4096 Apr  9 23:18 backgrounds
drwxr-xr-x 3 4096 Apr  9 23:18 Download
drwxr-xr-x 3 4096 Apr 10 13:49 Pictures
drwxr-xr-x 3 4096 Apr  9 23:14 Uncategorized

$ ls -la backgrounds/.meta/album_meta.json
-rw-r--r-- 1 161 Apr  9 23:18 backgrounds/.meta/album_meta.json
```

the album_meta.json files are populated with id, ownerid, albumname etc..

```
$ ./ente export
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 start sync
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 Sync files metadata for album Screenshots
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 Updating last sync time for album Screenshots to 2024-04-10 13:53:03.518434 +0200 CEST
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 Adding folder Screenshots for album Screenshots
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 Starting file download
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 total entries 0
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 process_files took 8.562µs
[photos-roughnecks@email.tld] 2024/04/10 14:13:04 sync done
```

The photos app says "no memories" and all the pictures I selected for backup have a cloud icon with a slash on top.

**Comment by mnvr** [comment]
> MissingRegion: could not find region configuration

Something is amiss in the s3 bucket configuration. The default configuration for the starter Docker compose file that we provided is here - https://github.com/ente-io/ente/blob/main/server/scripts/compose/credentials.yaml#L8. This should be getting picked automatically, but in your case it isn't so you'll need to make sure you've followed the steps exactly, e.g. 

```
git clone https://github.com/ente-io/ente
cd ente/server
docker compose up --build
```

Also see https://help.ente.io/self-hosting/. I understand that these are very generic recommendations I'm providing, but from your logs it seems very likely that there is something off in how you're starting the server, and if you try with a clean slate you might be able to isolate the missing bit.

If you're curious about the error, what is happening is that the client connects to the self hosted server and asks it for the URLs where it should store the files, but that fails

```
 ERRO[0195]handler.go:46 Error Request failed        
... - at /etc/ente/pkg/api/file.go:92 (FileHandler.GetUploadURLs) ---
```

and the reason is that the s3 bucket configuration is a bit wonky

```
museum-1           | Caused by: MissingRegion: could not find region configuration
```

Hope this helps!

**Reply by roughnecks** [reply]
> Something is amiss in the s3 bucket configuration. The default configuration for the starter Docker compose file that we provided is here - https://github.com/ente-io/ente/blob/main/server/scripts/compose/credentials.yaml#L8. This should be getting picked automatically, but in your case it isn't so you'll need to make sure you've followed the steps exactly, e.g.

Well, the fact is I configured my own s3 bucket (object storage on contabo), so maybe something is not right there..
How is the default s3 configuration meant to work? Is that only local or what?

**Reply by mnvr** [reply]
The default starter config creates a minio in the same docker compose cluster, and the default configuration uses these for its s3 storage.

I'd suggest first getting a local setup working. _Then_ move on to trying and modifying the primary hot bucket `b2-eu-cen` (but it's configurable - https://github.com/ente-io/ente/blob/eebb90fb40aea928ac2647557d759dca05ee6ade/server/configurations/local.yaml#L94 - and also the s3 bucket can be anywhere, the b2-eu-cen in the name is just a unique string constant). By default, replication is disabled (https://github.com/ente-io/ente/blob/eebb90fb40aea928ac2647557d759dca05ee6ade/server/configurations/local.yaml#L282) so you can just get rolling with one external bucket. Once you have _that_ working, you can enable replication too if you wish.

**Reply by roughnecks** [reply]
Hello,
I have a local s3 setup working but I really would like not to use that and go straight to my host's object storage. Is a configuration like this plausible?

```
s3:
    are_local_buckets: false
    contabo:
        key: I_have_it
        secret: I_have_it
        endpoint: bucker_url or just https://eu2.contabostorage.com ?
        region: I_dont_know
        bucket: the part that comes after bucket_url, like "roughnecks", when the bucket url is https://eu2.contabostorage.com/roughnecks or something else?
```

Thanks

**Reply by mnvr** [reply, marked as answer]
Yes, a configuration like this is possible, e.g. here is a guide from a community member who set up something similar - https://help.ente.io/self-hosting/guides/external-s3

In your case, the name of the bucket "contabo" is likely your issue - you cannot change the names without also making some changes in the source code. So just keep the name as they are in the default configuration. However, you can change all the other settings for the bucket, the endpoint / region etc.

```
s3:
    are_local_buckets: false
    b2-eu-cen:
        key: I_have_it
        secret: I_have_it
        endpoint: https://eu2.contabostorage.com or whatever is your S3-compatible service URL
        region: In some cases it doesn't matter, in some cases when you're using an external S3 service, it needs to match whatever your S3 storage service is telling you to set
        bucket: yes, this sounds correct -> the part that comes after bucket_url, like "roughnecks", when the bucket url is https://eu2.contabostorage.com/roughnecks 
```

You might also need to set `use_path_style_urls: true` unless your S3-storage provider supports the subdomain style URLs. For more details see https://github.com/ente-io/ente/blob/main/server/configurations/local.yaml#L136.

I think your config is already correct, you just need to change the name back from "contabo" to "b2-eu-cen", and maybe set `use_path_style_urls: true`.

Hope this helps!

**Reply by roughnecks** [reply]
Hey, thank you so much, it's working now!

**Reply by madroots** [reply]
Sorry to open this up again, its just I have the same problem but cannot seem to find solution. 
I have followed this: [Configuring S3](https://help.ente.io/self-hosting/guides/configuring-s3) and have added my configuration as follows:
```
db:
    host: postgres
    port: 5432
    name: ente_db
    user: pguser
    password: pgpass

s3:
    are_local_buckets: false
    use_path_style_urls: true
    wasabi-eu-central-2-v3:
        key: mykey
        secret: mysecret
        endpoint: ip where ente and minio server is running with opened port:3200
        region: eu-central-2
        bucket: wasabi-eu-central-2-v3
        compliance: false
```

I removed other 2 s3 configurations as per instructions.

I am still getting error: 

```
ERRO[0214]handler.go:47 Error Request failed                                error= --- at /etc/ente/pkg/api/file.go:115 (FileHandler.GetUploadURLs) ---
 --- at /etc/ente/pkg/controller/file.go:279 (FileController.GetUploadURLs) ---
 --- at /etc/ente/pkg/controller/file.go:891 (FileController.getObjectURL) ---
Caused by: MissingRegion: could not find region configuration req_id=7d66****************************ea32 user_id=1580********6439
```

I tried without the `use_path_style_urls: true` line too without success.
What am I missing?

**Reply by roughnecks** [reply]
should be set to true if you use minio: `are_local_buckets: false`

**Reply by mnvr** [reply]
`wasabi-eu-central-2-v3` is not the first bucket, you should rename it to the first bucket in the original list `b2-eu-cen` ([ref](https://github.com/ente-io/ente/blob/eebb90fb40aea928ac2647557d759dca05ee6ade/server/configurations/local.yaml#L97)) or specify the `hot_storage` option.

(The current way of configuring buckets is not the best, we're working on the sides to make it more ergonomic)

**Reply by mnvr** [reply]
@madroots I realize how the wording in the docs might've caused confusion - it's not the first bucket by order but rather the "first" bucket in the default list. I've rewritten this part on the [configuring s3 page](https://help.ente.io/self-hosting/guides/configuring-s3) to be (hopefully) clearer:

> When replication is turned off, only the first bucket (it must be named b2-eu-cen) is used, and you can ignore the other two. Use the hot_bucket option if you'd like to set one of the other predefined buckets as the "first" bucket.

**Reply by madroots** [reply]
Thank you for quick reply. I still cannot get it to work, although now it doesnt give any errors, however the files are not being uploaded. Here is my local.yml:

```
s3:
    # Override the primary and secondary hot storage. The commented out values
    # are the defaults.
    #
    hot_storage:
        primary: wasabi-eu-central-2-v3
        secondary: b2-eu-cen
    b2-eu-cen:
        key:
        secret:
        endpoint:
        region:
        bucket:
    wasabi-eu-central-2-v3:
        key:
        secret:
        endpoint:
        region:
        bucket:
```

and here is credentials.yaml:

```
db:
    host: postgres
    port: 5432
    name: ente_db
    user: pguser
    password: pgpass

s3:
    are_local_buckets: true
    use_path_style_urls: true
    wasabi-eu-central-2-v3:
        key: RSC5************RAO4
        secret: aesc********************************BgMe
        endpoint: 49.*****.250:3200
        region: eu-central-2
        bucket: wasabi-eu-central-2-v3
        compliance: false
```

It this correct please?
