### DISCUSSION TITLE
How do I configure a Backblaze bucket for self-hosting?

### DISCUSSION THREAD

**Discussion by forabi** [ente-io/ente#1764] [Q&A] [answered]
I think I've done everything right according to the documentation. I can confirm that all the pieces work fine if I'm using a local minio instance, but when trying to switch to a Backblaze bucket, I keep getting CORS missing issues in the browser when trying to view or upload photos.

```yaml
s3:
    are_local_buckets: false
    use_path_style_urls: false
    b2-eu-cen:
        key: xxx
        secret: xxx
        endpoint: s3.eu-central-003.backblazeb2.com
        region: eu-central-003
        bucket: xxx
```

I've run the following command to enable CORS for the bucket:

```bash
b2 bucket update --cors-rules "$(<./cors.json)" $B2_BUCKET_NAME allPrivate
```

```json
[
  {
    "corsRuleName": "allowUploadsAndDownloadsFromWebOrigin",
    "allowedOrigins": [
      "https://<MY_WEB_APP_DOMAIN>"
    ],
    "allowedHeaders": [
      "*"
    ],
    "allowedOperations": [
      "b2_download_file_by_id",
      "b2_download_file_by_name",
      "b2_upload_file",
      "b2_upload_part"
    ],
    "exposeHeaders": [
      "etag"
    ],
    "maxAgeSeconds": 3600
  }
]
```

yet:

![image](https://github.com/ente-io/ente/assets/1012761/a515420b-10a1-436e-81fc-2322664629d9)

The upload URL itself seems to match the S3-compatible URL listed in a files info on Backblaze, so it does seem like CORS isn't working.
