### DISCUSSION TITLE
Self-Hosting: Web app giving "Network Error", Android app is fine

### DISCUSSION THREAD

**Discussion by Handrail9** [ente-io/ente#2159] [Q&A]
Hello, I am trying to configure the web app to connect to my ente server but I am having an issue where the web server just says `Something went wrong, please try again (reason:Network Error) `when trying to log in. I've attached my docker compose file. which is located at /opt/ente/docker-compose.yaml (I used the web container Dockerfile from the post here on Github linked from the docs)
```
services:
  ente-museum:
    container_name: ente-museum
    build:
      context: server
      args:
        GIT_COMMIT: development-cluster
    ports:
      - 12121:3000 # web
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Pass-in the config to connect to the DB and MinIO
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - custom-logs:/var/logs
      - ./server/museum.yaml:/museum.yaml:ro
      - ./server/scripts/compose/credentials.yaml:/credentials.yaml:ro
      - ./server/data:/data:ro
    networks:
      - ente-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.ente-museum.entrypoints=web-secure,web
      - traefik.http.routers.ente-museum.rule=Host(`ente-museum.mydomain.tld`)
      - traefik.http.routers.ente-museum.tls=true
      - traefik.http.routers.ente-museum.tls.certresolver=production
      - traefik.http.routers.ente-museum.tls.domains[0].main=ente-museum.mydomain.tld
      - traefik.docker.network=ente-network
      - traefik.http.services.ente-museum.loadbalancer.server.port=8080

  ente-web:
    container_name: ente-web
    build:
      context: web
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_ENTE_ENDPOINT=ente-museum:8080
    network_mode: service:ente-museum
    depends_on:
      - ente-museum
    env_file:
      - ./server/.credentials.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.ente-web.entrypoints=web-secure,web
      - traefik.http.routers.ente-web.rule=Host(`ente.mydomain.tld`) || Host(`ente-albums.mydomain.tld`)
      - traefik.http.routers.ente-web.tls=true
      - traefik.http.routers.ente-web.tls.certresolver=production
      - traefik.http.routers.ente-web.tls.domains[0].main=ente.mydomain.tld
      - traefik.http.routers.ente-web.tls.domains[0].main=ente-albums.mydomain.tld
      - traefik.docker.network=ente-network
      - traefik.http.services.ente-web.loadbalancer.server.port=3000

  socat:
    container_name: ente-socat
    image: alpine/socat
    network_mode: service:ente-museum
    depends_on:
      - ente-museum
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    container_name: ente-postgres
    image: postgres:12
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "pguser"
        ]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ente-network

  minio:
    container_name: ente-minio
    image: minio/minio
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testtest
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    networks:
      - ente-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.ente-minio.entrypoints=web-secure,web
      - traefik.http.routers.ente-minio.rule=Host(`ente-minio.mydomain.tld`)
      - traefik.http.routers.ente-minio.tls=true
      - traefik.http.routers.ente-minio.tls.certresolver=production
      - traefik.http.routers.ente-minio.tls.domains[0].main=ente-minio.mydomain.tld
      - traefik.docker.network=ente-network
      - traefik.http.routers.ente-minio.service=ente-minio
      - traefik.http.services.ente-minio.loadbalancer.server.port=3200

  minio-provision:
    container_name: ente-minio-provision
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./scripts/compose/minio-provision.sh:/provision.sh:ro
      - minio-data:/data
    networks:
      - ente-network
    entrypoint: sh /provision.sh

volumes:
  custom-logs:
  postgres-data:
  minio-data:

networks:
  ente-network:
    name: ente-network

```

**Comment by mnvr** [comment]
It might be a CORS problem. The compose file example you're showing seems to be using a reverse proxy (`traefik`), my suggestion is to try to get it to work with a simpler localhost only setup (`docker compose up --build` + `NEXT_PUBLIC_ENTE_ENDPOINT=http://localhost:8080 yarn dev` as shown [here](https://github.com/ente-io/ente/blob/main/server/RUNNING.md#build-and-run-using-docker)), and then one by one add the bits specific to your setup (non-localhost domain, reverse proxy) to find where the problem lies.

**Comment by victornavorskie** [comment]
Hi, I am also trying to use Traefik but with pre-build docker image setup. 

```

services:
  museum:
    image: ghcr.io/ente-io/server
    container_name: ente-museum
    restart: unless-stopped
    ports:
      - 3333:8080
    #- 8033 # API
    #   - 2112 # Prometheus metrics
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Pass-in the config to connect to the DB and MinIO
      - ENTE_CREDENTIALS_FILE=scripts/credentials.yaml
    volumes:
      - /volume1/docker/ente/logs:/var/logs 
      - /volume1/docker/ente/museum.yaml:/museum.yaml:ro
      - ./scripts/credentials.yaml:/credentials.yaml:ro
      - /volume1/docker/ente/data:/data:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ente.entrypoints=https"
      - "traefik.http.routers.ente.rule=Host(ente.example..de)"
      - "traefik.http.routers.ente.tls=true"
      - "traefik.http.services.ente.loadbalancer.server.port=8080"
    networks:
      - internal
      - proxy

  # Resolve "localhost:3200" in the museum container to the minio container.
  socat:
    image: alpine/socat
    container_name: ente-socat
    restart: unless-stopped
    network_mode: service:museum
    depends_on:
      - museum
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    image: postgres:12
    container_name: ente-postgres
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "pguser"
        ]
      start_period: 40s
    #  start_interval: 1s
    volumes:
      - /volume1/docker/ente/db:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: ente-minio
    # Use different ports than the minio defaults to avoid conflicting
    # with the ports used by Prometheus.
    # ports:
    #   - 3200:3200 # API
    #   - 3201:3201 # Console
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testtest
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - /volume1/docker/ente/minio:/data
    networks:
      - internal

  minio-provision:
    image: minio/mc
    container_name: ente-mc
    depends_on:
      - minio
    volumes:
      - ./scripts/minio-provision.sh:/provision.sh:ro
      - /volume1/docker/ente/minio:/data
    networks:
      - internal
    entrypoint: sh /provision.sh

networks:
  internal:
  proxy:
    external: true

```

in browser with localhost :3333 error and in logs 
`ente-museum    | INFO[5481]request_logger.go:100 func3 outgoing                                      client_ip=192.168.0.254 client_pkg= client_version= h_latency=747.647µs latency_time=747.647µs query= req_body= req_id=3dded42b-79d7-471b-bb9c-4209342fedce req_method=GET req_uri=/ status_code=404 ua=Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0 user_id=0
ente-museum    | WARN[5481]main.go:956 urlSanitizer Unknown API: /  `

I have two questions:

1- Is it possible to add web app sanitizer to this docker compsoe without using build with same image and how ? 
2- What i am missing here is this compose missing something?
