### DISCUSSION TITLE
[Photos - Desktop] Could checksums be created with every release?

### DISCUSSION THREAD

**Discussion by taivlam** [ente-io/ente#2805] [Enhancements]
Currently SHA256 sums are generated with every Linux desktop release of Ente Auth, but currently there are no checksums generated with each release of Ente Photos desktop client.

I noticed this because I just submitted [`ente-desktop-bin`](https://mpr.makedeb.org/packages/ente-desktop-bin) on the [MPR](https://mpr.makedeb.org/).  Also, I am the maintainer of [`ente-auth-bin`](https://mpr.makedeb.org/packages/ente-auth-bin).

**Comment by mnvr** [comment]
The checksums are present in the various latest.yaml files that are generated:

<img width="187" alt="Screenshot 2024-08-22 at 09 32 55" src="https://github.com/user-attachments/assets/5df689df-2fda-421c-83af-6a6fe3b1413e">

---

^ screenshot from https://github.com/ente-io/photos-desktop/releases/tag/v1.7.3


That said, I agree the ergonomics can be improved. One particular thing that'll be nice is integrating [artifact attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds).

**Reply by taivlam** [reply]
How to I use the YAML file?  `latest-linux.yaml` reads as:
```
version: 1.7.3
files:
  - url: ente-1.7.3-x86_64.AppImage
    sha512: a8sIfkvz7MkO6YeSzHVObCyp2uYt8ifmmKLO6iVPfsuCJxeovUDsVXyTC7vM5RTwPTraOYT5xwzoB7epvXIddw==
    size: 387387099
    blockMapSize: 405231
  - url: ente-1.7.3-amd64.deb
    sha512: rKAfSjlhn4kbxDEn6bfJ/svmtbO0dXr0Dd5p6/vDQEkra3ljfeF7K81mBtGJACfyYmDdSARpGDNn8A+1sB/NFg==
    size: 207040522
  - url: ente-1.7.3-x86_64.rpm
    sha512: pxoXFtSRuOW+0SrtlpCIR32a0jFPsoKFxf9WDz/qdpNlP6iCMuLMzgeemUZB5DSULYKUFLAjWUT07QlclLP9lA==
    size: 206485421
path: ente-1.7.3-x86_64.AppImage
sha512: a8sIfkvz7MkO6YeSzHVObCyp2uYt8ifmmKLO6iVPfsuCJxeovUDsVXyTC7vM5RTwPTraOYT5xwzoB7epvXIddw==
releaseDate: '2024-08-21T09:39:13.733Z'
```

So, according to the YAML, the SHA512 checksum is:
```
rKAfSjlhn4kbxDEn6bfJ/svmtbO0dXr0Dd5p6/vDQEkra3ljfeF7K81mBtGJACfyYmDdSARpGDNn8A+1sB/NFg==
```

However, the SHA512 checksum for `ente-1.7.3-amd64.deb` (as an example) is this when I run `S sha512sum ente-1.7.3-amd64.deb` in the terminal:
```
aca01f4a39619f891bc43127e9b7c9fecbe6b5b3b4757af40dde69ebfbc340492b6b79637de17b2bcd6606d1890027f26260dd480469183367f00fb5b01fcd16
```

I'm not sure how to read the YAML's SHA512 checksum.
