### DISCUSSION TITLE
Self-Hosting Questions

### DISCUSSION THREAD

**Discussion by ytcalifax** [ente-io/ente#2813] [Q&A] [answered]
I'm currently trying to securely self-host myself an Ente instance (using the pre-built Docker image), however I seem to be hitting a roadblock due to me not figuring stuff out well enough from the docs. My current issue/question is the following:

When I upload some files (when I tested, out of ~400, only 20 files, all .DNGs and .MP4s) fail to upload and in the console of the docker containers I get signature verification errors. How would I go about Fixing those?

My configurations are the following:
compose.yaml:
```
services:
  museum:
    build:
      context: .
      args:
        GIT_COMMIT: development-cluster
    ports:
      - 8080:8080 # API
      - 2112:2112 # Prometheus metrics
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Pass-in the config to connect to the DB and MinIO
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - custom-logs:/var/logs
      - ./museum.yaml:/museum.yaml:ro
      - ./scripts/compose/credentials.yaml:/credentials.yaml:ro
      - ./data:/data:ro
    networks:
      - internal

  # Resolve "localhost:3200" in the museum container to the minio container.
  socat:
    image: alpine/socat
    network_mode: service:museum
    depends_on:
      - museum
    command: 'TCP-LISTEN:3200,fork,reuseaddr TCP:storage.[REDACTED].eu:3200'

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: [REDACTED]
      POSTGRES_DB: ente_db
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'ente_db', '-U', 'pguser']
      start_period: 40s
      start_interval: 1s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio
    # Use different ports than the minio defaults to avoid conflicting
    # with the ports used by Prometheus.
    ports:
      - 3200:3200 # API
      - 3201:3201 # Console
    environment:
      MINIO_ROOT_USER: [REDACTED]
      MINIO_ROOT_PASSWORD: [REDACTED]
    command: server /data --address "0.0.0.0:3200" --console-address "0.0.0.0:3201"
    volumes:
      - minio-data:/data
    networks:
      - internal

  minio-provision:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./scripts/compose/minio-provision.sh:/provision.sh:ro
      - minio-data:/data
    networks:
      - internal
    entrypoint: sh /provision.sh

volumes:
  custom-logs:
  postgres-data:
  minio-data:

networks:
  internal:
```

credentials.yaml
```
db:
  host: postgres
  port: 5432
  name: ente_db
  user: pguser
  password: [REDACTED]

s3:
  are_local_buckets: true
  b2-eu-ne:
    key: [REDACTED]
    secret: [REDACTED]
    endpoint: storage.[REDACTED].eu
    region: eu-ne-2
    bucket: b2-eu-ne
  wasabi-eu-ne-2-v3:
    key: [REDACTED]
    secret: [REDACTED]
    endpoint: storage.[REDACTED].eu
    region: eu-central-2
    bucket: wasabi-eu-ne-2-v3
    compliance: false
  scw-eu-ne-v3:
    key: [REDACTED]
    secret: [REDACTED]
    endpoint: storage.[REDACTED].eu
    region: eu-ne-2
    bucket: scw-eu-ne-v3
```

minio-provision.sh:

```
#!/bin/sh

# Script used to prepare the minio instance that runs as part of the development
# Docker compose cluster.

while ! mc config host add h0 https://storage.[REDACTED].eu [REDACTED] [REDACTED]
do
   echo "Waiting for minio..."
   sleep 0.5
done

cd /data

mc mb -p b2-eu-ne
mc mb -p wasabi-eu-ne-2-v3
mc mb -p scw-eu-ne-v3
```
museum.yml:
```
# Configuring museum
# ------------------
#
# 1. If the environment variable `ENVIRONMENT` is specified, then it is used to
#    load one of the files from the `configurations/` directory. If not present,
#    then by default `local.yaml` (this file) will get loaded.
#
# 2. Then, museum will look for a file named `museum.yaml` in the current
#    working directory. If found, this file will also be loaded, and entries
#    specified therein will override the defaults specified here.
#
# 3. If the "credentials-file" config option is set, then museum will also load
#    that and merge it in.
#
# 4. Config can be overridden with via environment variables (details below).
#
# Environment variables
# ---------------------
#
# All configuration options can be overridden via environment variables. The
# environment variable should have the prefix "ENTE_", and any nesting should be
# replaced by underscores.
#
# For example, the nested string "db.user" in the config file can alternatively
# be specified (or be overridden) by setting an environment variable named
# ENTE_DB_USER.
#
#
# Empty strings
# -------------
#
# The empty string indicates missing values (to match go convention).
#
# This also means that to override a value that is specified in local.yaml in a
# subsequently loaded config file, you should specify the key as an empty string
# (`key: ""`) instead of leaving it unset.
#
# ---

# Database connection parameters
db:
  host: postgres
  port: 5432
  name: ente_db
  # You might want to set this to "require" for production
  # See https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION
  sslmode: disable
  # These can be specified here, or alternatively provided via the environment
  # as ENTE_DB_USER and ENTE_DB_PASSWORD.
  user: [REDACTED]
  password: [REDACTED]
  # This can be used to provide parameters that are appended verbatim to the
  # generated DSN used for connecting to the DB.
  # extra:

# SMTP configuration (optional)
#
# Configure credentials here for sending mails from museum (e.g. OTP emails).
#
# The smtp credentials will be used if the host is specified. Otherwise it will
# try to use the transmail credentials. Ideally, one of smtp or transmail should
# be configured for a production instance.
smtp:
  host: 'smtp.resend.com'
  port: 587
  username: '[REDACTED]'
  password: '[REDACTED]'
  # The email address from which to send the email. Set this to an email
  # address whose credentials you're providing.
  email: '[REDACTED]'

# Various low-level configuration options
internal:
  # Hardcoded verification codes, useful for logging in when developing.
  #
  # Uncomment this and set these to your email ID or domain so that you don't
  # need to peek into the server logs for obtaining the OTP when trying to log
  # into an instance you're developing on.
  hardcoded-ott:
    emails:
      - '[REDACTED]'
  # List of user IDs that can use the admin API endpoints.
  admins: []
```
