### DISCUSSION TITLE
docker stops after starting

### DISCUSSION THREAD

**Discussion by arifroni** [ente-io/ente#3057] [Q&A]
Hello, i used this docker compose to run all the container. But after few minutes all of them stops. From the log file i couldn't understand anything. Can someone help?

docker-compose.yaml
```
# networks:
#   default:
#     name: ente
#     ipam: 
#       config:
#         - subnet: 172.XX.X.0/27 #change Xs as necessary to select an unused subnet
#   #uncomment the below and change the name 'proxy' to the name of your reverse proxy network if necessary
#   #proxy:
#     #external: true

services:
  museum:
    image: ghcr.io/ente-io/server
    ports:
      - 8880:8080 #change port number before the `:` as necessary to avoid port clashes
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - custom-logs:/var/logs
      - ./museum.yaml:/museum.yaml:ro
      - ./credentials.yaml:/credentials.yaml:ro

  socat:
    image: alpine/socat
    network_mode: service:museum
    depends_on:
      - museum
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    image: postgres:12
    ports:
      - 5432:5432 #change port number before the `:` as necessary to avoid port clashes
    environment:
      POSTGRES_USER: pguser #change
      POSTGRES_PASSWORD: pgpass #change
      POSTGRES_DB: ente_db
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "pguser" #change if you have changed `POSTGRES_USER` above
        ]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 3200:3200 # API #change port number before the `:` as necessary to avoid port clashes
      - 3201:3201 # Console #change port number before the `:` as necessary to avoid port clashes
    environment:
      MINIO_ROOT_USER: <user>#change
      MINIO_ROOT_PASSWORD: <pass>#change
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data


  minio-provision:
    image: minio/mc
    container_name: minio-provision
    depends_on:
      - minio
    volumes:
      - ./minio-provision.sh:/provision.sh:ro
      - minio-data:/data
    entrypoint: sh /provision.sh

volumes:
  custom-logs:
  postgres-data:
  minio-data:
```

logs from 4 containers
![image](https://github.com/user-attachments/assets/4b4d7431-c266-422b-a3a9-6b745c0ce7a1)
