### DISCUSSION TITLE
Github Action workflow to auto-push new Ente Auth/Photos releases to winget-packages

### DISCUSSION THREAD

**Discussion by jo-chemla** [ente-io/ente#3950] [Enhancements]
Current package releases for Ente Auth, CLI (+ Photos Desktop, see [other repo](https://github.com/ente-io/photos-desktop/actions/runs/11676694511/workflow)) are done manually by community, eg see for auth [here](https://github.com/microsoft/winget-pkgs/pull/174671) and [there](https://github.com/microsoft/winget-pkgs/pull/175109), so the ente winget packages are not up-to-date - current version available is 4.0.2 while newest github release is [4.1.0](https://github.com/ente-io/ente/releases?q=tag%3Aauth-v4). 

It would be useful that every new github release of Ente also pushes the updated packages to the winget-pkgs repo via a PR. This can be easily done with the winget-releaser@v2 Github action that can be incorporated into the current workflows for [auth-release](https://github.com/ente-io/ente/blob/main/.github/workflows/auth-release.yml). 

Should a similar discussion be opened on Ente Photo Desktop repo so every [new release](https://github.com/ente-io/photos-desktop/releases) also gets auto pushed to winget-pkgs? Thanks!

### Describe the solution you'd like to see.

Here is a reference article based on [Winget-Releaser@v2 Github Action](https://github.com/russellbanks/Komac?tab=readme-ov-file#usage-with-github-actions-winget-releaser-). Below is an action yml files made to keep the winget package up-to-date on every github release, via Github Actions. 

Requires:
 - You will need to create a classic Personal Access Token (PAT) with public_repo scope.
 - This token should be added as a repository secret by creating a [new repo secret](https://github.com/Jacalz/rymdport/settings/secrets/actions/new) with name WINGET_ACC_TOKEN and value the token
 - Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under the same account/organization as the project's repository. If you are forking winget-pkgs on a different account (e.g. bot/personal account), you can use the fork-user input to specify the username of the account where the fork is present.

```yaml
name: Publish to WinGet
on:
  release:
    types: [ released ]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: ente-io.auth-desktop
          token: ${{ secrets.WINGET_TOKEN }}
          installers-regex: 'ente\-auth\-\w*\-installer\.exe$'  

```
