### DISCUSSION TITLE
Enable self-hosting on Synology NAS

### DISCUSSION THREAD

**Discussion by StefanOltmann** [ente-io/ente#4057] [Enhancements]
I'd like to self host ente on my Synology DS920+ withing the Container Manager and noticed here several problems.

First you can't have a container use the official 5432 port. This must be remapped to something else to not collide with the internal Postgres of Synology DSM:

```
  postgres:
    image: postgres:15
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
      PGPORT: 5433
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "pguser",
          "-p",
          "5433"
        ]
      start_period: 40s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal
```

After that I noticed I can't change the password "pgpass" for Postgres or museum won't start up.

And lastly Synology doesn't have a proper volume support. It would be great to change that in a way that all data is actually written to the "data" mount point.

I managed to start my instance, but the "data" folder is empty.

Would be great if you could make this working smooth with Synology NAS.

**Comment by thisislawatts** [comment]
hey @StefanOltmann. Thanks for raising this, I have a Synology device on order. 

Regarding: _First you can't have a container use the official 5432 port. This must be remapped to something else to not collide with the internal Postgres of Synology DSM_

Have you looked into overriding the port using an environment variable?

```
# Environment variables
# ---------------------
#
# All configuration options can be overridden via environment variables. The
# environment variable should have the prefix "ENTE_", and any nesting should be
# replaced by underscores.
#
# For example, the nested string "db.user" in the config file can alternatively
# be specified (or be overridden) by setting an environment variable named
# ENTE_DB_USER.
```
source: https://github.com/ente-io/ente/blob/main/server/configurations/local.yaml#L18-L27

**Reply by StefanOltmann** [reply]
It worked with the `PGPORT: 5433` I shared.

My suggestion is changing the default port, so it will run on Synology out of the box.

**Comment by StefanOltmann** [comment]
I really don't get why it's so hard to self host Ente.

My intention was to set it up again in a clean way and document that for others, but the system doesn't work.

What I wanted to change here is:
- Using a custom Postgres port, because the default one is already used.
- Use local folders instead of volumes, because volumes don't work that great on Synology.
- Use better passwords than just `test` and `testtest` (even if the services are not reachable)

The empty folders exist and I can start up the system and register, but it won't upload files.
There is no error message, it just stucks.

minio-provision spams `mc: <ERROR> Unable to initialize new alias from the provided credentials.`

---

`compose.yml`:
```
services:
  museum:
    image: ghcr.io/ente-io/server
    ports:
      - 8080:8080 # API
      - 2112:2112 # Prometheus metrics
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Pass-in the config to connect to the DB and MinIO
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    volumes:
      - /volume1/docker/ente-io/credentials.yaml:/credentials.yaml:ro
      - /volume1/docker/ente-io/custom-logs:/var/logs:rw
      # - /volume1/docker/ente-io/museum.yaml:/museum.yaml:ro
    networks:
      - internal

  # Resolve "localhost:3200" in the museum container to the minio container.
  socat:
    image: alpine/socat
    network_mode: service:museum
    depends_on:
      - museum
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    image: postgres:15
    # Don't use the default port as this is already internally used on a Synology NAS.
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: ente
      POSTGRES_PASSWORD: fF5zqfidJn3CCBi
      POSTGRES_DB: ente_db
      PGPORT: 5433
    # Wait for postgres to be accept connections before starting museum.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "ente",
          "-p",
          "5433"
        ]
      start_period: 40s
    volumes:
      - /volume1/docker/ente-io/postgres-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  minio:
    image: minio/minio
    # Use different ports than the minio defaults to avoid conflicting
    # with the ports used by Prometheus.
    ports:
      - 3200:3200 # API
      - 3201:3201 # Console
    environment:
      MINIO_ROOT_USER: ente
      MINIO_ROOT_PASSWORD: WSsc7d7s2MW8vYG
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - /volume1/docker/ente-io/minio-data:/data:rw
    networks:
      - internal

  minio-provision:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - /volume1/docker/ente-io/minio-provision.sh:/minio-provision.sh:ro
      - /volume1/docker/ente-io/minio-data:/data:rw
    networks:
      - internal
    entrypoint: sh /minio-provision.sh

networks:
  internal:
```

`credentials.yml`:
```
db:
    host: postgres
    port: 5433
    name: ente_db
    user: ente
    password: fF5zqfidJn3CCBi

s3:
    are_local_buckets: true
    b2-eu-cen:
        key: ente
        secret: WSsc7d7s2MW8vYG
        endpoint: localhost:3200
        region: eu-central-2
        bucket: b2-eu-cen
    wasabi-eu-central-2-v3:
        key: ente
        secret: WSsc7d7s2MW8vYG
        endpoint: localhost:3200
        region: eu-central-2
        bucket: wasabi-eu-central-2-v3
        compliance: false
    scw-eu-fr-v3:
        key: ente
        secret: WSsc7d7s2MW8vYG
        endpoint: localhost:3200
        region: eu-central-2
        bucket: scw-eu-fr-v3
```

`minio-provision.sh`:
```
#!/bin/sh

# Script used to prepare the minio instance that runs as part of the development
# Docker compose cluster.

while ! mc config host add h0 http://minio:3200 ente WSsc7d7s2MW8vYG
do
   echo "waiting for minio..."
   sleep 0.5
done

cd /data

mc mb -p b2-eu-cen
mc mb -p wasabi-eu-central-2-v3
mc mb -p scw-eu-fr-v3
```
