### DISCUSSION TITLE
Default security

### DISCUSSION THREAD

**Discussion by mwelsch** [ente-io/ente#5212] [Q&A]
Hello,
I am setting up Ente on my own server using the docker image and compose provided. However I do have some security concerns over the default settings and am wondering why it is nowhere explained how to harden the application properly? I do not understand the full ecosystem and hence ask myself if all of this is intended and if it save to run the docker compose with the default values on my public server?

Guides I used and searched for
[[Github docker.md] Using public ente.io image rather than building](https://github.com/ente-io/ente/blob/main/server/docs/docker.md)
[[Github] server/readme](https://github.com/ente-io/ente/tree/main/server#readme)
[[Github] server/running.md](https://github.com/ente-io/ente/blob/main/server/RUNNING.md)
[[ente.io] Self-hosting getting started (and I read through most of the other guides aswell)] (https://help.ente.io/self-hosting/)

## Postgres
The port `5432` is publicly available. Is that needed? It also says nowhere to change the default postgres user or password while beeing exposed to the internet??

## MinIO
It just says `use different ports than minio default to avoid conflicting with the port used by promotheus`. Does that mean I should change the publicly exposed ports? Then the `command` part of the docker compose file would also have to change. Again it is nowhere hinted that I should change the root user or password??

## Custom keys
Because of the [community guide on how to self host with external s3](https://help.ente.io/self-hosting/guides/external-s3) I discoverd that also some internal keys are used. In no other guide it tells me to generate or change those.

In the [server/configurations/local.yaml](https://github.com/ente-io/ente/blob/main/server/configurations/local.yaml) it says:
```
# Key used for encrypting customer emails before storing them in DB
#
# To make it easy to get started, some randomly generated values are provided
# here. But if you're really going to be using museum, please generate new keys.
# You can use `go run tools/gen-random-keys/main.go` for that.
key:
    encryption: yvmG/RnzKrbCb9L3mgsmoxXr9H7i2Z4qlbT0mL3ln4w=
    hash: KXYiG07wC7GIgvCSdg+WmyWdXDAn6XKYJtp/wkEU7x573+byBRAYtpTP0wwvi8i/4l37uicX1dVTUzwH3sLZyw==

# JWT secrets
#
# To make it easy to get started, a randomly generated values is provided here.
# But if you're really going to be using museum, please generate new keys. You
# can use `go run tools/gen-random-keys/main.go` for that.
jwt:
    secret: i2DecQmfGreG6q1vBj5tCokhlN41gcfS2cjOs9Po-u8=
```
