### DISCUSSION TITLE
Add flatpak package

### DISCUSSION THREAD

**Discussion by muznyo** [ente-io/ente#587] [Enhancements]
AppImages are nice, but flatpaks are much better on Linux in my opinion. They are supported by repositories and sandboxed.

Here is a [comparision](https://linuxhint.com/snap_vs_flatpak_vs_appimage/)

**Comment by mnvr** [comment]
Hey @muznyo, thank you for this suggestion!

I agree with the idea - Our wish was to support as many Linux packaging mechanisms as possible, but at least support both Flatpak and AppImages. 

However, we ran into an issue when we tried integrating Flatpak into our build pipeline. What we found is that we could only get AppImages to reliably work with the automatic app update mechanism that we were using (We use Electron). We haven't looked since, it's been a while, maybe that issue has been fixed now though.

And then there is another issue related to publishing to Flathub (https://www.electron.build/configuration/flatpak):

![flatpak](https://user-images.githubusercontent.com/24503581/196728555-a6ffd564-6157-4c5c-bd67-6f3536ff2f14.png)

Again, I'm sure if we dig deep enough we'll be able to find workarounds. But since functionally AppImages provided the baseline functionality, we let it be when we last looked, hoping to get back to this at a later point. We'll take another peek at this soon though.

Thanks!

**Reply by cassidyjames** [reply]
Hey @mnvr, I'm a volunteer with Flathub and I'd be happy to help you out getting your app published to Flathub. While you can actually go the `electron-builder` route to produce either a single-file bundle (and then talk to the Flathub admins to get upload credentials), an easier route is to use another artifact as the source for your Flatpak (several apps on Flathub do this today with tarballs, Debian packages, or even AppImages as the source); as long as there's some reproducible way to get a Flatpak from your source, that gets encoded into the manifest and then Flathub's infrastructure reproducibly processes that for each update.

We just documented how you can even implement automatic publishing of updates to Flathub when your source repository changes: https://docs.flathub.org/docs/for-app-authors/updates#automatically-publish-updates

I'd be happy to answer any questions or help out however I can, here. I use Ente Photos personally and would love to see it in the app store on Endless OS and Fedora Silverblue—plus places like Steam Deck's desktop mode. :)

**Reply by mnvr** [reply]
Hey! Thank you for this info 🙏 This is actually quite timely - we've moved our stuff over to this monorepo and as part of this we're revisiting all of our packaging and github actions etc. I hope to be able to get to the packaging modifications for Photos Desktop app soon, and I'll use your info to try and add this to the build pipeline from the get go (It might take a bit of time, I'm trying to also update our outdated version of electron-builder, but if that takes too long I'll just do the packaging changes first and deal with that later).

>  I use Ente Photos personally

❤️

> I'd be happy to answer any questions or help out however I can, here

Thanks again. I'll ask if I get stuck. Cheers!

**Comment by NiffirgkcaJ** [comment]
I hope this goes through! Ente Auth is amazing!

**Comment by ZethiaZ** [comment]
I'd love ente auth and photos on flathub too!

**Comment by theamazing0** [comment]
I was trying to package Ente Auth as a flatpak but ran into a few errors that I'm not sure why are happening. If someone else more knowledge or the app developers are interested, maybe this could help.

### Manifest:
```yaml
id: auth.ente.io
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: ente_auth
finish-args:
  - --device=dri
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=x11
  - --share=network
  - --socket=session-bus
modules:
  - name: ente-auth
    buildsystem: simple
    build-commands:
      - chmod +x ente-auth-*.AppImage
      - ./ente-auth-*.AppImage --appimage-extract
      - ls ./squashfs-root/usr
      # - install -D ./squashfs-root/usr/share/icons/hicolor/128x128/apps/ente_auth.png /app/share/icons/hicolor/128x128/apps/${FLATPAK_ID}.png
      # - install -D ./squashfs-root/usr/share/icons/hicolor/256x256/apps/ente_auth.png /app/share/icons/hicolor/256x256/apps/${FLATPAK_ID}.png
      - mkdir -p ${FLATPAK_DEST}
      - install -d "${FLATPAK_DEST}/lib"
      - cp -r ./squashfs-root/lib/* "${FLATPAK_DEST}/lib/"
      - cp -r ./squashfs-root/usr/lib/* "${FLATPAK_DEST}/lib/"
      - install -d "${FLATPAK_DEST}/data"
      - cp -r ./squashfs-root/data/* "${FLATPAK_DEST}/data/"
      - install -D ./squashfs-root/ente_auth -t /app/bin
      # - mv ./squashfs-root /app/bin
    sources:
      - type: file
        url: https://github.com/ente-io/ente/releases/download/auth-v3.1.3/ente-auth-v3.1.3-x86_64.AppImage
        sha256: 1de25049af644c9e27705d87af51c0435528ff0a89066a91444695ccebe13698
        only-arches: [x86_64]
        x-checker-data:
          type: json
          url: https://api.github.com/repos/ente-io/ente/releases/latest
          version-query: .tag_name | sub("^v"; "")
          url-query: .assets[] | select(.name|match("ente-auth-.*\\.AppImage")) |
            .browser_download_url
```

### Build Command:
```
flatpak-builder --force-clean --install-deps-from=flathub --repo=repo --user --install builddir auth.ente.io.yml
```

### Error when launching with Wayland permission enabled
```
flatpak run auth.ente.io --user

(ente_auth:2): Gdk-CRITICAL **: 19:32:18.776: gdk_gl_context_make_current: assertion 'GDK_IS_GL_CONTEXT (context)' failed

** (ente_auth:2): WARNING **: 19:32:18.776: Failed to initialize GLArea: No GL implementation is available

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.777: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.778: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.778: gtk.dart: failed to call method: No engine to send to

** (ente_auth:2): WARNING **: 19:32:18.778: gtk.dart: failed to call method: No engine to send to
```

### Error when launching with Wayland disabled (so XWayland gets used)
```
flatpak run auth.ente.io --user

Gtk-Message: 19:32:30.959: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:32:30.959: Failed to load module "pk-gtk-module"
Gtk-Message: 19:32:30.961: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:32:30.962: Failed to load module "pk-gtk-module"
embedder.cc (1442): 'FlutterEngineCreateAOTData' returned 'kInvalidArguments'. Invalid ELF path specified.

** (ente_auth:2): WARNING **: 19:32:31.113: Failed to start Flutter engine: Failed to create AOT data

** (ente_auth:2): WARNING **: 19:32:31.115: gtk.dart: failed to call method: No engine to send to
```
