### DISCUSSION TITLE
General questions about Ente and Feature requests

### DISCUSSION THREAD

**Discussion by Heshmatkhah** [ente-io/ente#5911] [Enhancements]
Hi
I'm new to Ente and I'm enjoying it a-lot!

I face some problems and I have some question:

1. How can I add a **not recognized person face** to an image?
    I have some image with many people on them, the app detects most of them, but some persons are missing, I need a way to add them to the Image: similar to apple photos: ![Apple Photos](https://media.idownloadblog.com/wp-content/uploads/2022/08/Tag-multiple-faces-in-a-single-photo-on-Mac.jpg)

2. When I need to save a person face in an image, I can't search my existing saved persons!
   ![Search in existing persons](https://github.com/user-attachments/assets/70fab378-ebf8-43fa-a990-83966feffe4c)

3. Can I have a description for each person in addition to title? If no, Can I contribute to source code and add this?

4. The import from Apple photos, doesn't support Image Title/Description/Keyword form the `XMP` files? does it import other information from the `XMP` file? or it will ignore it completly?

5. I self-hosted the Ente on my server and here is the web part of the docker compose file:
   The server is behind NGINX installed on the host to handle HTTPS traffic:
   ```
     web:
       image: ghcr.io/ente-io/web
       restart: always
       # Uncomment what you need to tweak.
       ports:
         - 127.0.0.1:3000:3000 # Photos web app
         - 127.0.0.1:3001:3001 # Accounts
         - 127.0.0.1:3002:3002 # Public albums
         - 127.0.0.1:3003:3003 # Auth
         - 127.0.0.1:3004:3004 # Cast
       environment:
         NEXT_PUBLIC_ENTE_ENDPOINT: https://ente.mydomain.local
         ENTE_API_ORIGIN: https://ente.mydomain.local
         ENTE_ALBUMS_ORIGIN: https://ente.mydomain.local
   
   ```
   Do I need to have all those services? can I use the `web`/`accounts`/`cast`/`albums`/`auth` from ente.io with my own instance?

6. How to edit Description of multiple image at once? (like apple photos)
7. How to sync only some image for phone gallery to the Ente istead of full album?

Thank you
