### DISCUSSION TITLE
EmptyStaticCreds: static credentials are empty

### DISCUSSION THREAD

**Discussion by MatzeKitt** [ente-io/ente#5917] [Q&A] [answered]
Unfortunately, I can’t get self-hosting to work properly, uploads won’t work. When trying to upload a file, the following error message is logged:

> 2025-05-15 06:09:15.293187+00:00[31mERRO[0m[0006]handler.go:50 Error Request failed                                [31merror[0m= --- at /etc/ente/pkg/api/file.go:117 (FileHandler.GetUploadURLs) ---
2025-05-15 06:09:15.293261+00:00--- at /etc/ente/pkg/controller/file.go:312 (FileController.GetUploadURLs) ---
2025-05-15 06:09:15.293288+00:00--- at /etc/ente/pkg/controller/file.go:979 (FileController.getObjectURL) ---
2025-05-15 06:09:15.293339+00:00Caused by: EmptyStaticCreds: static credentials are empty

I try to self-host on a TrueNAS SCALE with a custom app.

`compose.yaml`:

```yaml
services:
  minio:
    command: server /data --address ":3200" --console-address ":3201"
    environment:
      MINIO_ROOT_PASSWORD: *snip*
      MINIO_ROOT_USER: *snip*
    image: minio/minio
    ports:
      - '3200:3200'
      - '3201:3201'
    volumes:
      - /mnt/SSData/apps/ente/minio-data:/data
  minio-provision:
    depends_on:
      - minio
    entrypoint: sh /provision.sh
    image: minio/mc
    volumes:
      - /mnt/SSData/apps/ente/minio-provision.sh:/provision.sh:ro
      - /mnt/SSData/apps/ente/minio-data:/data
  museum:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/ente-io/server
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    ports:
      - '8080:8080'
    volumes:
      - /mnt/SSData/apps/ente/credentials.yaml:/credentials.yaml:ro
      - /mnt/SSData/apps/ente/museum.yaml:/museum.yaml:ro
      - /mnt/SSData/apps/ente/data:/data:ro
  postgres:
    environment:
      POSTGRES_DB: ente_db
      POSTGRES_PASSWORD: *snip*
      POSTGRES_USER: pguser
    healthcheck:
      start_interval: 1s
      start_period: 40s
      test: pg_isready -q -d ente_db -U pguser
    image: postgres:15
    volumes:
      - /mnt/SSData/apps/ente/postgres-data:/var/lib/postgresql/data
  socat:
    command: TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200
    depends_on:
      - museum
    image: alpine/socat
    network_mode: service:museum
  web:
    image: ghcr.io/ente-io/web
    ports:
      - '3000:3000'
      - '3006:3001'
```

`credentials.yaml`

```yaml
db:
      host: postgres
      port: 5432
      name: ente_db
      user: pguser
      password: *snip*

s3:
      are_local_buckets: true
      b2-eu-cen:
         key: *snip*
         secrect: *snip*
         endpoint: http://minio:3200
         region: eu-central-2
         bucket: b2-eu-cen
```

`museum.yaml`

```yaml
key:
      encryption: *snip*
      hash: *snip*

jwt:
      secret: *snip*

s3:
      are_local_buckets: true
      b2-eu-cen:
         key: *snip*
         secrect: *snip*
         endpoint: http://minio:3200
         region: eu-central-2
         bucket: b2-eu-cen
```

I know, adding the `s3` configuration to both the `credentials.yaml` as well as the `museum.yaml` doesn’t make sense, but since credentials don’t seem to reach the services according to the error message, I tried everything …

Any guidance on how to fix this error? 🤔
