### DISCUSSION TITLE
Ente Self-Hosted Migration Guide

### DISCUSSION THREAD

**Discussion by zulfiqarlaili** [ente-io/ente#5967] [Q&A]
# Ente Self-Hosted Migration Guide

This guide explains how to migrate Ente (photos, users, and metadata) between two self-hosted instances running on different VMs.

## Prerequisites
- Access to **old VM** (`192.168.1.18` in this example) and **new VM** (`192.168.1.47`).
- `docker-compose` installed on both VMs.
- Backup of credentials (encryption keys, JWT secrets, PostgreSQL/MINIO passwords).

---

## Step 1: Preserve Encryption Keys
**Without these, your data will be unreadable!**

1. On the **old VM**, locate your `museum.yaml` or `local.yaml` file.
2. Copy these values:
   ```yaml
   key:
     encryption: "<OLD_ENCRYPTION_SECRET>"
     hash: "<OLD_HASH_SECRET>"
   jwt:
     secret: "<OLD_JWT_SECRET>"
   ```
3. On the **new VM**, replace the corresponding values in `museum.yaml`.

---

### Export from Old VM
```bash
# On old VM
docker exec -t ente-postgres pg_dump -U <POSTGRES_USER> -d <POSTGRES_DB> > ente_dump.sql
```
- Replace `<POSTGRES_USER>` and `<POSTGRES_DB>` with your old instance’s credentials.

### Import to New VM
1. Transfer `ente_dump.sql` to the new VM.
2. **Stop Ente** on the new VM:
   ```bash
   docker compose down
   ```
3. Drop and recreate the database (temporarily match old credentials in `compose.yaml`):
   ```yaml
   # compose.yaml (new VM)
   environment:
     POSTGRES_USER: "<OLD_POSTGRES_USER>"
     POSTGRES_PASSWORD: "<OLD_POSTGRES_PASSWORD>"
   ```
4. Import the dump:
   ```bash
   docker exec -i ente-postgres-new psql -U <OLD_POSTGRES_USER> -d <POSTGRES_DB> < ente_dump.sql
   ```
5. Restore new VM’s original PostgreSQL credentials in `compose.yaml`.

---

### Configure MinIO Client (`mc`)
Run these commands **on one machine** (e.g., the new VM):

1. Install `mc`:
   ```bash
   wget https://dl.min.io/client/mc/release/linux-amd64/mc
   chmod +x mc && sudo mv mc /usr/local/bin/
   ```

2. Create aliases for both MinIO instances:
   ```bash
   # Old MinIO (old VM)
   mc alias set oldminio http://<OLD_VM_IP>:3200 \
     "<OLD_MINIO_ROOT_USER>" \
     "<OLD_MINIO_ROOT_PASSWORD>"

   # New MinIO (new VM)
   mc alias set newminio http://<NEW_VM_IP>:3200 \
     "<NEW_MINIO_ROOT_USER>" \
     "<NEW_MINIO_ROOT_PASSWORD>"
   ```

### Copy Buckets
```bash
mc mirror oldminio/b2-eu-cen newminio/b2-eu-cen
mc mirror oldminio/wasabi-eu-central-2-v3 newminio/wasabi-eu-central-2-v3
mc mirror oldminio/scw-eu-fr-v3 newminio/scw-eu-fr-v3
```

---

## Step 4: Update Configuration on New VM

1. Verify `museum.yaml` on the new VM:
   ```yaml
   s3:
     are_local_buckets: true
     b2-eu-cen:
       endpoint: "<NEW_VM_IP>:3200"  # Use new VM's IP
       key: "<NEW_MINIO_ROOT_USER>"
       secret: "<NEW_MINIO_ROOT_PASSWORD>"
   ```

2. Ensure PostgreSQL credentials in `compose.yaml` match the restored database.

---

## Step 5: Start the New Instance
```bash
docker compose up -d
```

---

## Step 6: Verify Migration
1. Access the new instance at `http://<NEW_VM_IP>:3000`.
2. Log in with an existing user account.
3. Confirm photos and metadata are intact.

---

## Troubleshooting
- **Database Errors**: Check logs with `docker logs ente-postgres-new`.
- **MinIO Connection Issues**:
  ```bash
  curl -I http://<OLD_VM_IP>:3200/minio/health/live
  curl -I http://<NEW_VM_IP>:3200/minio/health/live
  ```
- **Decryption Failures**: Double-check `key` and `jwt` values in `museum.yaml`.

---

## Final Notes
- **Backups**: Regularly backup PostgreSQL (`postgres-data` volume) and MinIO (`minio-data` volume).
- **Version Compatibility**: Ensure both instances run the same Ente version.
- **Reverse Proxy**: Configure HTTPS via Nginx/Caddy for production use.

---

**Example Credentials Table** (Replace with your own):

| Component          | Old VM                     | New VM                     |
|---------------------|----------------------------|----------------------------|
| PostgreSQL User     | `pguser`                   | `pguser-new`               |
| PostgreSQL Password | `pgpass`                   | `pgpass-new`               |
| MinIO Root User     | `test`                     | `minio-user`               |
| MinIO Root Password | `testtest`                 | `minio-password`           |
| Encryption Secret   | `yvmG/RnzKrbCb9L3mgsmox...`| (Same as old VM)           |
