### DISCUSSION TITLE
Help with Passkeys in a Self-Hosted setup

### DISCUSSION THREAD

**Discussion by jordanhandy** [ente-io/ente#6112] [Q&A] [answered]
Hello,

Passkeys don't seem to be working with my setup.  Hoping for some guidance.  When I visit my accounts URL (as a redirect from Passkeys under the Security menu), a popup says "could not retrieve passkeys" or similar.  When I attempt to name a new passkey, I'm met with "couldn't add passkey".

Some of my config:

museum.yaml
```yaml
webauthn:
    # Our "Relying Party" ID. This scopes the generated credentials.
    # See: https://www.w3.org/TR/webauthn-3/#rp-id
    rpid: accounts.mydomain.com
    # Whitelist of origins from where we will accept WebAuthn requests.
    # See: https://github.com/go-webauthn/webauthn
    rporigins:
       # - "http://localhost:3001"
        - "https://accounts.mydomain.com"
...

apps:
  accounts: https://accounts.mydomain.com

```

compose.yaml
```yaml
...
web:
    image: ghcr.io/ente-io/web
    # Uncomment what you need to tweak.
    ports:
      - 3000:3000 # Photos web app
      - 3001:3001 # Accounts
      - 3002:3002 # Public albums
      - 3003:3003 # Auth
      - 3004:3004 # Cast
    environment:
      NEXT_PUBLIC_ENTE_ENDPOINT: https://web.mydomain.com
      NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT: https://albums.mydomain.com
      NEXT_PUBLIC_ENTE_ACCOUNTS_URL: https://accounts.mydomain.com
```

When I visit the page, the server logs show a `GET` taking place, but I don't see much else.  Wondering if there is another logging location to check

In the above `*.mydomain` is changed to my actual TLD

Thanks for the help
