### DISCUSSION TITLE
CLI - Offer Docker Image via a registry

### DISCUSSION THREAD

**Discussion by creedda** [ente-io/ente#711] [Enhancements]
Hello!

This is fantastic! Super excited about this CLI and what it affords for some of us power users.
Very excited.

Some suggestions for MVP2:

Can we include in the workflows in our GitHub actions for this repo a workflow to automatically build and publish the docker image to a registry like docker.io?

Something like this?:

```
name: Build and Push Docker Image to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'  # This will run the workflow when you push a new tag in the format v0.0.0
      - 'v*.*.*-beta.*'
      
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
       run: docker build -t ente:latest . --no-cache --force-rm
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the Docker image
        run: docker-compose up -d
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


```

Or if you wanted to stick with everything in goreleaser, it looks like it supports it (I'm just personally less familiar with how to write up the code)

https://goreleaser.com/customization/docker/#customization

I don't want to step on toes by adding this as a PR as it requires the team to have their own Docker Hub account, and I do not know what registry the team would prefer to use. This would be an easier way of ensuring that users always have the latest version of the CLI. (Auto-updates through something like watchtower)

Thank you for looking at my suggestion! Again thank you for this incredible feature! Looking forward to its growth.
