### ISSUE TITLE
Why does starting Ente on iOS or Android always show "Encrypting backup..." and a loading spinner for long durations

### ISSUE THREAD

**Issue by maffinca69** [ente-io/ente#2601]
### Discussed in https://github.com/ente-io/ente/discussions/2529

<div type='discussions-op-text'>

<sup>Originally posted by **pczern** July 24, 2024</sup>
On my android device the spinner appears for 2mins after start and on my iOS device for a longer time and only disappears as it seems first after viewing images.</div>

**Comment by maffinca69** [comment]
I fixed it. I change s3 config scripts/compose/credentials.yaml:
```
db:
    host: postgres
    port: 5432
    name: ente_db
    user: pguser
    password: pgpass

s3:
    are_local_buckets: true
    b2-eu-cen:
        key: test
        secret: testtest
        endpoint: 192.168.1.110:3200
        region: eu-central-2
        bucket: b2-eu-cen
    wasabi-eu-central-2-v3:
        key: test
        secret: testtest
        endpoint: 192.168.1.110:3200
        region: eu-central-2
        bucket: wasabi-eu-central-2-v3
        compliance: false
    scw-eu-fr-v3:
        key: test
        secret: testtest
        endpoint: 192.168.1.110:3200
        region: eu-central-2
        bucket: scw-eu-fr-v3
```
Replaced 192.168.1.110 on server address in your network (instead of localhost)
