### ISSUE TITLE
ente accounts is ignoring API URL settings while creating passkey

### ISSUE THREAD

**Issue by MatzeKitt** [ente-io/ente#5955]
### Description

I’ve setup ente to run on a local system with external access via different subdomains:

- API: ente.domain.tld
- Photos: ente-albums.domain.tld
- Accounts: ente-accounts.domain.tld

Despite this, by trying to create a passkey via ente-accounts.domain.tld, an error stated that the passkeys could not be retrieved, and the browser console shows this error message:

> [Error] [error] Failed to fetch passkeys: SyntaxError: The string did not match the expected pattern.
json@[native code]
@https://ente-accounts.domain.tld/_next/static/chunks/8209-4276d4d4952ccd2a.js:1:6045
	error (_app-5a9d4b1114bdb56b.js:2:27471)
	(anonyme Funktion) (passkeys-f9e54c7fd28226fd.js:1:14545)

When ignoring the error above and try to create a new passkey by entering a name and pressing the button "Create passkey", the following error message appears in the console:

> [Error] [error] HTTP 405  (/passkeys/registration/begin) {"url":"https://ente-accounts.domain.tld/passkeys/registration/begin"}
	error (_app-5a9d4b1114bdb56b.js:2:27471)
	w (8209-4276d4d4952ccd2a.js:1:1441)
	(anonyme Funktion) (8209-4276d4d4952ccd2a.js:1:6600)

As per my understanding, the API should be used, so https://ente.domain.tld/passkeys/registration/begin.

My configuration:

`compose.yaml`

```yaml
services:
  museum:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    image: ghcr.io/ente-io/server
    ports:
      - '8080:8080'
    volumes:
      - /mnt/SSData/apps/ente/credentials.yaml:/credentials.yaml:ro
      - /mnt/SSData/apps/ente/museum.yaml:/museum.yaml:ro
      - /mnt/SSData/apps/ente/data:/data:ro
  postgres:
    environment:
      POSTGRES_DB: ente_db
      POSTGRES_PASSWORD: *snip*
      POSTGRES_USER: pguser
    healthcheck:
      start_interval: 1s
      start_period: 40s
      test: pg_isready -q -d ente_db -U pguser
    image: postgres:15
    volumes:
      - /mnt/SSData/apps/ente/postgres-data:/var/lib/postgresql/data
  web:
    image: ghcr.io/ente-io/web
    ports:
      - '3000:3000'
      - '3006:3001'
```

`credentials.yaml`

```yaml
key:
      encryption: *snip*
      hash: *snip*

jwt:
      secret: *snip*

db:
      host: postgres
      port: 5432
      name: ente_db
      user: pguser
      password: *snip*

s3:
      are_local_buckets: true
      b2-eu-cen:
         key: ente-user
         secret: *snip*
         endpoint: https://minio.domain.tld
         region: eu-central-2
         bucket: ente
```

`museum.yaml`

```yaml
apps:
      accounts: https://ente-accounts.domain.tld

webauthn:
      rpid: ente-accounts.domain.tld
      rporigins:
        - "https://ente-accounts.domain.tld"

internal:
    admins:
        - 1580559962386438
```

### Version

1.0.10

### What product are you using?

Ente Photos

### What platform are you using?

Server

**Comment by jordanhandy** [comment]
@MatzeKitt 
I had this same issue myself.

Try changing your `rpid` to your root domain, like so

```
webauthn:
      rpid: domain.tld
      rporigins:
        - "https://ente-accounts.domain.tld"
```
