### ISSUE TITLE
Make docker compose for self hosters less confusing

### ISSUE THREAD

**Issue by FSaurenbach** [ente-io/ente#5970]
Hello, I have noticed that album sharing needs two separate web instances running on different ports(https://help.ente.io/self-hosting/faq/sharing). But from the docker compose sample it is very easy to think that album sharing works with a single web instance as the port for public albums is already listed in the main web instance:  
```
ports:
      - 3000:3000 # Photos web app
      # - 3001:3001 # Accounts
      - 3002:3002 # Public albums
      # - 3003:3003 # Auth
      # - 3004:3004 # Cast
```
So to make it less confusing could you please edit the compose.yaml so that it looks something like this with two seperate instances? 

```
web:
    image: ghcr.io/ente-io/web
    ports:
      - 3000:3000 # Photos web app
      - 3001:3001 # Accounts
    environment:
      ENTE_API_ORIGIN: https://api.domain.tld:443 
      ENTE_ALBUMS_ORIGIN: https://albums.domain.tld:443
      NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT: https://albums.domain.tld:443

albums:
    image: ghcr.io/ente-io/web
    ports:
      - 3002:3002 # Public albums
    environment:
      ENTE_API_ORIGIN: https://api.domain.tld:443 
      ENTE_ALBUMS_ORIGIN: https://albums.domain.tld:443
      NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT: https://albums.domain.tld:443

```
Thank you very much! Ente is absolutely amazing btw!
