### ISSUE TITLE
self hosted Accounts expired after update

### ISSUE THREAD

**Issue by ghost** [ente-io/ente#6282]
### Description

Hi,
I've just updated my ente self hosted by doing compose pull and then build.
Now I can't upload anything to the server.
Checking on the logs, I can see this

museum-1           |  --- at /etc/ente/pkg/controller/file.go:297 (FileController.GetUploadURLs) ---
museum-1           | Caused by: all bonus & plan expired
museum-1           |  --- at /etc/ente/pkg/controller/usage.go:108 (UsageController.canUploadFile) ---
museum-1           | Caused by: no Active Subscription req_id=ser_xxxxxxxxx user_id=xxxxxxxxxxxxx

I have 2 accounts that I've extended to 1Tb as per the docs.
ANy help is appreciatted, as I can't rollback as I'm running on a Pi with backup of photos but not the server itslef.
Thanks.

**Comment by nexryai** [comment]
I also encountered the same problem. I can no longer upload photos even though I was able to back them up until now.  
I was able to resolve the issue by running the below query on the database.
```sql
UPDATE subscriptions
# 2040-01-01 00:00:00
SET expiry_time = 2208988800000000;
```

**Comment by mio-moto** [comment]
Just adding to this, in the containerized setup:
```yaml
mio@synology:/volume1/Sinkhole/ente-io$ cat compose.yaml 
services:
  # ... 
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    # Wait for postgres to accept connections before starting museum.
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "ente_db",
          "-U",
          "pguser"
        ]
      start_period: 40s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:
```

you can do that on a running system, by:

```sh
$ sudo docker exec -it -u postgres 88e8cbacda16 psql ente_db pguser 
ente_db-# UPDATE subscriptions SET expiry_time = 9223372036854775807
ente_db-# \q
```

Next time the app refreshes, the subscription error should be gone.
